### PR TITLE
freifunk: increase user experience

### PR DESCRIPTION
**Pull request by FreifunkUFO**
a better SSID to start with

### CODE REVIEW

**Comment by FreifunkUFO** [comment]
hey @dangowrt , its better than an ask for changing within wifi-scan.

**Comment by ilario** [comment]
This was opened long time ago but I suppose it's still valid?
Merging!

**Comment by dangowrt** [comment]
On Thu, May 20, 2021 at 04:25:07AM -0700, Ilario Gelmetti wrote:
> This was opened long time ago but I suppose it's still valid?
> Merging!

I'd say NACK because it will result in nodes leaving this network name
instead of chaning it to a unique name as it should be.
This is exactly the reason why it was put in that way, so that we would
be sure the value would be changed to something specific for the
community, as otherwise we will experience routing difficulties in the
moment there are two devices with that ap_ssid 'FreifunkLibremesh' in
the network which are not actually connected on Layer-2 (as in having
an Ethernet wire between them or same batman-adv mesh VLAN bridged).

I see that this change will increase the risk of having to deal with
that problem again (as we had to in the beginning of the deployment
5 years ago which is why I put such an overly obvious default...)

**Comment by ilario** [comment]
OK, sorry for merging. I cannot revert as I'm on the phone, can anyone prepare a PR with a commit reverting this change?

**Pull request merged**
