### PR TITLE
all: rename lime-defauts -> lime-community

### PR DESCRIPTION
**Pull request by dangowrt**
In order to convert community profiles into packages a new config file
lime-community was introduced as lime-defaults cannot be used for that.
This is because lime-defaults is already being shipped with the
lime-system package and hence cannot be installed again by any other
package. Hence rename lime-defaults to lime-community in all profiles.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by ilario** [comment]
Looks good to me.

**Comment by spiccinini** [comment]
Also I think it is ok. When we updated the quintanalibre profile we did many changes as some things were not needed anymore. So I would let communities know that they should at least review and clean the settings and files.

**Comment by ilario** [comment]
Aaand we need to communicate this change on the mailing lists, at least. Otherwise I fear that people will not do a pull before (force) pushing their own network-profile.

**Comment by aparcar** [comment]
Ping

**Comment by ilario** [comment]
No negative opinion, so I'm going to merge, but please announce this change on lime-users mailing list and on Riot chat.

**Pull request merged**
