### PR TITLE
Add Moinho's network profile

### PR DESCRIPTION
**Pull request by luandro**

### CODE REVIEW

**Review by nicopace — APPROVED** [review]

**Comment by aparcar** [comment]
Nico please squash a PR that contains 28 commits or let the original author do it, but this messes up the commit history

**Comment by nicopace** [comment]
@aparcar how come... github doesn't allow to merge without checking that is mergeable before...
@luandro can you talk to aparcar about this?

**Comment by luandro** [comment]
I'm sorry, I tried squashing everything and failed. Thought it would be easier as it's merged. Can we do a rebase to fix this?

**Comment by aparcar** [comment]
@nicopace in the GitHub interface you canchoose between merge, rebase and squash when applying a PR
@luandro merging to master branch and then squashing would mess up the commit history as it requires a force push. You can locally run something like `git rebase -i <commit hash>` which allows you to change the commit history locally, then push via `git push -f <your branch>`.

**Comment by luandro** [comment]
I did the rebase, but I guess I missed the `-f` when pushing, it didn't squash.

**Comment by aparcar** [comment]
Please check this out https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request merged**
