### PR TITLE
babeld VLAN

### PR DESCRIPTION
**Pull request by digitigrafo**
fix

### CODE REVIEW

**Comment by G10h4ck** [comment]
I suggests you use VLAN 17 for babeld to keep compatibility with defaults ;)

**Comment by ilario** [comment]
Txorry, my fault, I suggested 18 (I always remember that incorrectly).





-- 
Inviato dal mio smartstone

**Comment by ilario** [comment]
@G10h4ck if you could jump on the disucussions running here
https://ml.ninux.org/pipermail/bologna/2019-November/thread.html it would
be very useful.

-- 
Inviato dal mio smartstone

**Comment by G10h4ck** [comment]
> @G10h4ck if you could jump on the disucussions running here https://ml.ninux.org/pipermail/bologna/2019-November/thread.html it would be very useful.
> […](#)
> -- Inviato dal mio smartstone

An error occurred during a connection to ml.ninux.org. PR_END_OF_FILE_ERROR

**Comment by ilario** [comment]
>
> An error occurred during a connection to ml.ninux.org.
> PR_END_OF_FILE_ERROR
>

Works for me, you can subscribe from here
 https://ml.ninux.org/mailman/listinfo/bologna


-- 
Inviato dal mio smartstone

**Pull request closed without merging**
